# Generated by Django 5.0.4 on 2024-06-12 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kondisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kondisi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ukuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ukuran', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_warna', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sepatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sepatu', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.bahan')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.kategori')),
                ('kondisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.kondisi')),
                ('ukuran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ukuran')),
                ('warna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.warna')),
            ],
        ),
    ]
